version: '2'

services:
  pytest-rethinkdb:
    build:
      context: .
    volumes:
      - ./docs:/usr/src/app/docs
      - ./tests:/usr/src/app/tests
      - ./pytest_rethinkdb.py:/usr/src/app/pytest_rethinkdb.py
      - ./setup.py:/usr/src/app/setup.py
